#! /bin/sh
# Copy and setup autoProcessTV scripts to allow sabnzb access to them through the docker shared volume
cp -a /srv/sickbeard/autoProcessTV /data/
chown -R downloads:downloads /data

# Run supervisor
/usr/bin/supervisord -c /etc/supervisor/supervisord.conf
